### PR TITLE
Support multiple imports

### LINKED ISSUE #14: Support multiple modules.
Ember is migrating from `import isEnabled from 'ember-metal/features'` to `import { isFeatureEnabled } from 'ember-metal';`.  During the transition (while the code is being updated piece by piece) it would be nice to instruct this plugin to simply process both modules. Unfortunately, that doesn't seem possible today.

One possible solution is something like:

```js
{
  "plugins": [["feature-flags", [
    {
      "import": {
          "module": "ember-metal/features"
      },
      "features": {
          "new-feature": "disabled"
      }
    },
    {
      "import": {
          "module": "ember-metal",
          "name": "isFeatureEnabled"        
      },
      "features": {
          "new-feature": "disabled"
      }
    }
  ]]
}
```

@mmun - Thoughts?

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves #14 

/cc @mmun @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
@mmun - Have you had a chance to review?

@krisselden - We need to check if Babel 6 allows us to use the plugin with different configuration. If it does, we do not need to port this PR to master branch.

**Comment by mmun** [comment]
@rwjblue This is good and I see what @Turbo87 meant now. I thought you would need to specify two sets of flags.

**Comment by mmun** [comment]
Actually I am fine with porting this PR to master as is as long as long as all the imports share the same feature flags.

**Comment by rwjblue** [comment]
Right, that is definitely true for Embers use case, but I could see other scenarios (in userland) where different feature flags would be desired. Hopefully Babel 6 comes through and allows the same plugin twice (with different config).

**Comment by Turbo87** [comment]
I call YAGNI :wink: 

If we decide we need to extend it we could still allow flags to be defined inside the imports array, but for now this should be fine.

**Pull request merged**
